language: objective-c

xcode_project: Volontair.xcodeproj
xcode_scheme: Volontair
osx_image: xcode7.2

before_install:
 - brew update
 - brew outdated xctool || brew upgrade xctool

script:
 - xctool -workspace Volontair.xcworkspace -scheme Volontair -sdk iphonesimulator build test -freshInstall CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

notifications:
  slack: projectb-avans:siOpU3NrKhK1f4IkjwfKx0el
  on_success: change
  on_failure: always
