language: objective-c

xcode_project: Volontair.xcodeproj
xcode_scheme: Volontair
osx_image: xcode7.3

before_install:
- brew update || brew update
- brew outdated xctool || brew upgrade xctool

script:
- xctool -project Volontair.xcodeproj -scheme Volontair -sdk iphonesimulator build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
