language: objective-c

xcode_project: Volontair.xcodeproj
xcode_scheme: Volontair
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.2

script:
- xctool -project Volontair.xcodeproj -scheme Volontair build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
